name: petalpost
description: "PetalPost couples notes app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  home_widget: ^0.6.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  signature: ^5.5.0
  path_provider: ^2.1.3
  path: ^1.9.0
  record: ^5.1.2
  just_audio: ^0.9.36
  audio_session: ^0.1.20
  permission_handler: ^11.3.1
  scratcher: ^2.5.0
  mixpanel_flutter: ^2.2.1
  animations: ^2.0.11
  flutter_slidable: ^3.1.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  fake_cloud_firestore: ^3.0.2
  riverpod_test: ^0.1.5

dependency_overrides:
  record_linux:
    path: packages/record_linux

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo.png
    - assets/branding/name.png
